-- ==========================================
-- BasuraVision: Supabase Database and Storage Setup
-- ==========================================
-- Run this script in the Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- 1. Create the 'reportes' table
CREATE TABLE IF NOT EXISTS public.reportes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_seguimiento TEXT NOT NULL UNIQUE,
    latitud DOUBLE PRECISION NOT NULL,
    longitud DOUBLE PRECISION NOT NULL,
    tipo_basura TEXT NOT NULL,
    urgencia_base INT NOT NULL DEFAULT 5,
    urgencia_dinamica DOUBLE PRECISION NOT NULL DEFAULT 5.0,
    mensaje_ciudadano TEXT,
    tracking_step INT NOT NULL DEFAULT 0, -- 0: Reportado, 1: En Proceso, 2: En Limpieza, 3: Resuelto
    imagen_url TEXT,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    clases_softmax JSONB DEFAULT '[]'::jsonb
);

-- Enable Row Level Security (RLS) on reportes
ALTER TABLE public.reportes ENABLE ROW LEVEL SECURITY;

-- Create policies for public access (Anon can read and insert)
CREATE POLICY "Permitir lectura publica de reportes" ON public.reportes
    FOR SELECT USING (true);

CREATE POLICY "Permitir insercion publica de reportes" ON public.reportes
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Permitir actualizacion publica de reportes" ON public.reportes
    FOR UPDATE USING (true);


-- 2. Storage Setup for 'trash-images' bucket
-- Note: Make sure to first create a bucket named 'trash-images' from the Supabase Storage dashboard and make it PUBLIC.
-- If you want to enable public access and uploads via RLS policies on storage:

-- Insert bucket configuration if not exists
INSERT INTO storage.buckets (id, name, public) 
VALUES ('trash-images', 'trash-images', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Storage policies for 'trash-images'
-- Allow anonymous/public select (viewing photos)
CREATE POLICY "Permitir lectura publica de imagenes" ON storage.objects
    FOR SELECT TO public USING (bucket_id = 'trash-images');

-- Allow anonymous/public upload (saving photos)
CREATE POLICY "Permitir subida publica de imagenes" ON storage.objects
    FOR INSERT TO public WITH CHECK (bucket_id = 'trash-images');

-- Allow anonymous/public delete (when marking as resolved)
CREATE POLICY "Permitir borrado publico de imagenes" ON storage.objects
    FOR DELETE TO public USING (bucket_id = 'trash-images');
